//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipesparties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public equipesparties()
        {
            this.scoresequipesparties = new HashSet<scoresequipesparties>();
        }
    
        public int idEquipePartie { get; set; }
        public int idPartie { get; set; }
        public int idEquipe { get; set; }
        public Nullable<bool> estGagnante { get; set; }
    
        public virtual equipes equipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scoresequipesparties> scoresequipesparties { get; set; }
        public virtual parties parties { get; set; }
    }
}
