//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipesparticipants
    {
        public int idEquipeParticipant { get; set; }
        public int idEquipe { get; set; }
        public int idParticipant { get; set; }
    
        public virtual equipes equipes { get; set; }
        public virtual participants participants { get; set; }
    }
}
