//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class jeuxcomptes
    {
        public int idJeuCompte { get; set; }
        public int idJeu { get; set; }
        public int idParticipant { get; set; }
        public string nomCompte { get; set; }
        public string detail { get; set; }
        public System.DateTime dateCreation { get; set; }
        public System.DateTime lastUpdated { get; set; }
    
        public virtual jeux jeux { get; set; }
        public virtual participants participants { get; set; }
    }
}
