//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class jeuxcomptes
    {
        public int idJeuCompte { get; set; }
        public int idJeu { get; set; }
        public int idParticipant { get; set; }
        public string nomCompte { get; set; }
        public string detail { get; set; }
        public System.DateTime dateCreation { get; set; }
        public System.DateTime lastUpdated { get; set; }
    
        public virtual jeux jeux { get; set; }
        public virtual participants participants { get; set; }
    }
}
