//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int idMessage { get; set; }
        public int idCompte { get; set; }
        public string contenu { get; set; }
        public System.DateTime dateEnvoie { get; set; }
    
        public virtual comptes comptes { get; set; }
    }
}
