//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class parties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public parties()
        {
            this.equipesparties = new HashSet<equipesparties>();
        }
    
        public int idPartie { get; set; }
        public int idTour { get; set; }
        public int numPartie { get; set; }
        public bool estTermine { get; set; }
        public Nullable<System.TimeSpan> dureeJeu { get; set; }
        public System.DateTime dateFin { get; set; }
        public System.DateTime lastUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<equipesparties> equipesparties { get; set; }
        public virtual tours tours { get; set; }
    }
}
