//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class postes
    {
        public int idPoste { get; set; }
        public int idLocal { get; set; }
        public int idEtatPoste { get; set; }
        public Nullable<int> idCompte { get; set; }
        public int numeroPoste { get; set; }
        public string commentaire { get; set; }
        public System.DateTime lastUpdated { get; set; }
    
        public virtual comptes comptes { get; set; }
        public virtual etatspostes etatspostes { get; set; }
        public virtual locaux locaux { get; set; }
    }
}
