//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class prixtournois
    {
        public int idPrixTournoi { get; set; }
        public int idPrix { get; set; }
        public int idTournoi { get; set; }
    
        public virtual prix prix { get; set; }
        public virtual tournois tournois { get; set; }
    }
}
