//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class scoresequipesparties
    {
        public int idScoreEquipePartie { get; set; }
        public int idStatistiqueJeu { get; set; }
        public int idEquipePartie { get; set; }
        public decimal valeur { get; set; }
    
        public virtual equipesparties equipesparties { get; set; }
        public virtual statistiquesjeux statistiquesjeux { get; set; }
    }
}
