//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class statistiquesjeux
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public statistiquesjeux()
        {
            this.scoresequipesparties = new HashSet<scoresequipesparties>();
        }
    
        public int idStatistiqueJeu { get; set; }
        public int idJeu { get; set; }
        public int idStatistique { get; set; }
    
        public virtual jeux jeux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scoresequipesparties> scoresequipesparties { get; set; }
        public virtual statistiques statistiques { get; set; }
    }
}
