//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LamaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class tours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tours()
        {
            this.parties = new HashSet<parties>();
        }
    
        public int idTour { get; set; }
        public int idTournoi { get; set; }
        public int numTour { get; set; }
        public bool estFinal { get; set; }
        public System.DateTime dateDebut { get; set; }
        public Nullable<System.DateTime> dateFin { get; set; }
        public System.DateTime lastUpdated { get; set; }
    
        public virtual tournois tournois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<parties> parties { get; set; }
    }
}
