//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanManager.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipesparticipants
    {
        public int idEquipeParticipant { get; set; }
        public int idEquipe { get; set; }
        public int idParticipant { get; set; }
    
        public virtual equipes equipes { get; set; }
        public virtual participants participants { get; set; }
    }
}
