//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanManager.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int idMessage { get; set; }
        public int idCompte { get; set; }
        public string contenu { get; set; }
        public System.DateTime dateEnvoie { get; set; }
    
        public virtual comptes comptes { get; set; }
    }
}
