//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanManager.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class prixtournois
    {
        public int idPrixTournoi { get; set; }
        public int idPrix { get; set; }
        public int idTournoi { get; set; }
    
        public virtual prix prix { get; set; }
        public virtual tournois tournois { get; set; }
    }
}
