//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanManager.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class statistiquesjeux
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public statistiquesjeux()
        {
            this.scoresequipesparties = new HashSet<scoresequipesparties>();
        }
    
        public int idStatistiqueJeu { get; set; }
        public int idJeu { get; set; }
        public int idStatistique { get; set; }
    
        public virtual jeux jeux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<scoresequipesparties> scoresequipesparties { get; set; }
        public virtual statistiques statistiques { get; set; }
    }
}
