//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanManager.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class tournoislocaux
    {
        public int idTournoiLocal { get; set; }
        public int idTournoi { get; set; }
        public int idLocal { get; set; }
        public int idCompte { get; set; }
    
        public virtual comptes comptes { get; set; }
        public virtual locaux locaux { get; set; }
        public virtual tournois tournois { get; set; }
    }
}
